### ISSUE TITLE
Insert chart gui (like obsidian-charts)

### ISSUE THREAD

**Issue by kkollsga** [Dmitriy-Shulha/obsidian-plotly#11]
Great work getting plotly graph into obsidian! Can't thank you enough =)

A couple of improvement points that would be great:
- Insert chart gui, like obsidian-graphs have to create basic line and scatter charts as a starting point (others can be added later, plotly has a huge amount of setups, but at least basic ones would be wonderful), personally I think yaml works best with obsidian
- Width and height scaling to auto fill, or partially fill screen.
- Standard color scheme to match active theme

**Comment by Dmytro-Shulha** [comment]
I'm glad you find this plugin useful :)

I have created several issues based on your improvement points (see #14, #15, #16).

Thanks for your feedback!
