### ISSUE TITLE
How to draw gantt chart?

### ISSUE THREAD

**Issue by vosandr** [Dmitriy-Shulha/obsidian-plotly#5]
I need to add this codeblocks https://plotly.com/python/gantt/

**Comment by Dmytro-Shulha** [comment]
Hello!
Link that you have attached is python implementation while my plugin provide only javascript support.
Unfortunately, I haven't managed to find JS example of Gantt plot on plotly site, I assume this plot is a new one.

Python example of Gantt uses this `px.timeline` function or something, that i haven't managed to find any equivalent in [JS codebase](https://github.com/plotly/plotly.js).

I will look into how this can be implemented within current plotly.js version, but as far as I can see, this kind of plot is not supported yet.

I will post an update when find suitable solution for this. (If you find a solution faster than me - please post it here, any help will be appreciad)

As an alternative, I may suggest [mermaid Gantt](https://mermaid-js.github.io/mermaid/#/gantt) chart, which is supported by Obsidian as one of the core features. Not as powerful as plotly for sure, but still may be useful.

**Comment by Dmytro-Shulha** [comment]
Regarding d3 installation, it would not help to make your example work.
But if you need it for other purposes, just download *.min.js file from [official site](https://d3js.org/), place it somewhere inside your Obsidian vault and put a path to it inside dataviewjs block (plugin provides a command for pasting such example).
There are [various](http://bl.ocks.org/dk8996/5449641) [gantt](https://codepen.io/jey/details/jmClJ) [implementations](https://github.com/scholtzan/d3-gantt), that are based on d3, not require plotly and may be copied into dataviewjs block.

But I absolutely not sure if copy-pasting them would even work without fine-tuning and additional changes.

**Comment by vosandr** [comment]
I am still a beginner but I liked this solution https://github.com/scholtzan/d3-gantt. How to install this? d3 I want to copy to .plugins/plotly folder, is it possible?

**Comment by vosandr** [comment]
I want doing plugin, which the export notes by search results.  How difficult is it to do?

**Comment by Dmytro-Shulha** [comment]
> I want doing plugin, which the export notes by search results. How difficult is it to do?

Unfortunately, I have no idea (it needs further investigation), and this one, as far as I can see, is definitely unrelated to initial topic of this issue (gantt chart).
I suggest to ask this question on Discord official server or on forum, see links [here](https://obsidian.md/community).
